apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: Jenkins-role
subjects:
  - kind: ServiceAccount
    name: jenkins-admin
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: Jenkins-role